#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE ROLE innovation_affectation WITH LOGIN SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:CLsJ9+Wg0aZfGnwR/E133Q==$vwIq9z1Rs+A5K1juvFT3c/c9HVNufQX9dEkxaY+LfoM=:c9ohPrciXzX5xcAf9DoocWdf15ale4ZeyGmJT7m5jG4=';

  CREATE ROLE innovation_collaborator WITH LOGIN SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:1IGjT8tBHanWX3dQvMs8Tg==$K1IIaQbuOJ82kkZWv2KaiKdjs/laGaJR+Xdg8ukhzGA=:MdV7Bp/KxP7Aga6ovUnq/JyJASAhXfr4sMHh5Fju0Ow=';

  CREATE ROLE innovation_project WITH LOGIN SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:pINHxAtlBpQ1ZD8G9E0Epg==$I28s5/p1aeVW0dSh6Sz2bH5R6j5UCn+ihy7oD17UbRI=:HZTzTWxYsNQaIf+BpzJdWy354WgX5DMLbDT1f5ByIiU=';

  CREATE DATABASE affectation
    WITH
    OWNER = innovation_affectation
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

    CREATE DATABASE collaborator
    WITH
    OWNER = innovation_collaborator
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

    CREATE DATABASE project
        WITH
        OWNER = innovation_project
        ENCODING = 'UTF8'
        TABLESPACE = pg_default
        CONNECTION LIMIT = -1;

EOSQL

